// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class leaderboards
{
        public const string leaderboard_mejores_tiempos__pista_tres = "CgkI9J7KgKwcEAIQCQ"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_doce = "CgkI9J7KgKwcEAIQEg"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_cuatro = "CgkI9J7KgKwcEAIQCg"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_nueve = "CgkI9J7KgKwcEAIQDw"; // <GPGSID>
        public const string achievement_imparable = "CgkI9J7KgKwcEAIQAQ"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_dos = "CgkI9J7KgKwcEAIQCA"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_diecinueve = "CgkI9J7KgKwcEAIQGQ"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_ocho = "CgkI9J7KgKwcEAIQDg"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_trece = "CgkI9J7KgKwcEAIQEw"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_dieciseis = "CgkI9J7KgKwcEAIQFg"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_quince = "CgkI9J7KgKwcEAIQFQ"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_dieciocho = "CgkI9J7KgKwcEAIQGA"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_diez = "CgkI9J7KgKwcEAIQEA"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_veinte = "CgkI9J7KgKwcEAIQGg"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_once = "CgkI9J7KgKwcEAIQEQ"; // <GPGSID>
        public const string achievement_intocable = "CgkI9J7KgKwcEAIQAg"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_siete = "CgkI9J7KgKwcEAIQDQ"; // <GPGSID>
        public const string achievement_dr_kalavera = "CgkI9J7KgKwcEAIQBA"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_catorce = "CgkI9J7KgKwcEAIQFA"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_diecisiete = "CgkI9J7KgKwcEAIQFw"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_uno = "CgkI9J7KgKwcEAIQBw"; // <GPGSID>
        public const string achievement_invencible = "CgkI9J7KgKwcEAIQAw"; // <GPGSID>
        public const string achievement_fast_and_yellow = "CgkI9J7KgKwcEAIQBg"; // <GPGSID>
        public const string achievement_the_shark = "CgkI9J7KgKwcEAIQBQ"; // <GPGSID>
        public const string achievement_corredor = "CgkI9J7KgKwcEAIQAA"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_seis = "CgkI9J7KgKwcEAIQDA"; // <GPGSID>
        public const string leaderboard_mejores_tiempos__pista_cinco = "CgkI9J7KgKwcEAIQCw"; // <GPGSID>

}

